### ISSUE TITLE
Запуск нескольких копий 

### ISSUE THREAD

**Issue by macik** [lorents17/iCatalyst#10]
При запуске из под Far manager пишет:

```
-------------------------------------------
 Attention: running 2 of Image Catalyst.   

 Press Enter to continue.                  
-------------------------------------------
```

Если запустить еще один из другого окна — напишет `Attention: running 3 of Image Catalyst.`.
Тут понятно добавилась еще одна. Но почему при первой запуске пишет что 2 копии?

На старой версии такого не было (или вообще проверки не было)...

При запуске драг-н-дропом такого нет.

**Comment by macik** [comment]
Еще потестировал. Дело не в Far'е. Похоже дело в [ConEmu](http://www.conemu.ru/), из под которого работает Far.

**Comment by res2001** [comment]
Привет!
Обнаружения запущенных копий происходит по поиску в заголовках окон названия IC вот такой конструкцией:
tasklist /fo csv /v /nh | find /i /c "%name% %version%"
Возможно, после ошибок из прошлого сообщения заголовок окна остался установленным IC, хотя он уже и не работает. По идее достаточно закрыть все консольные окна где ранее запускался IC и в новом окне должно все быть нормально.

**Comment by macik** [comment]
Для тестов грохнул старые окна и процессы, запустил «с нуля» Far(через ConEmu). Ситуация повторяется — 2 процесса.

Вот как выглядят в таскменеджере процессы, которые относятся к Фару. 
![image](https://cloud.githubusercontent.com/assets/1009926/11297752/983aa0bc-8f8b-11e5-9a85-5135cd200e7a.png)

При запуске батника рождается еще один дочерний фару процесс с командной строкой.

А для чего нужно обнаружение запущенных копий? Может просто создавать файл-флаг, что процесс запущен. В конце удалять?

**Comment by res2001** [comment]
Far всегда запускает cmd когда в его коммандной строке что-нибудь выполняешь.
Обнаружение запущенных копий сделали для того чтобы IC не отъдал ресурсы сам у себя. Т.к. оптимизация выполняется в многозадачном режиме, то оптимизация может съесть все процессорное время. Запущенный еще один экземпляр IC будет только мешать в этом случае. Это актуально для настроек по умолчанию.
Файл-флаг - это хорошо, но в случае падения IC файл-флаг останется не удаленным и пока пользователь вручную его не удалит IC работать не будет.

После закрытия всех консольных окон и нового запуска IC заработал?

**Comment by res2001** [comment]
Проблема с двойным запуском из-за ConEmu.
Для проверки запусти IC из-под ConEmu и оставь окно висеть.
Открой другую консоль (лучше не в ConEmu) и выполни команду:
tasklist /fo csv /v /nh | find /i "Image Catalyst"
Увидишь 3 процесса с окном, содержащим в заголоке Image Catalyst, один из них это запущенная команда, другой это окно ConEmu, и последний это сам IC.
Смысл в том, что ConEmu своим заголовком делает заголовок активного консольного окна. И похоже, что хоть задачи в ConEmu работают в его окне, на самом деле это отдельные процессы со своими окнами. В таком же стиле работает и Chrome, например.
В общем предлагаю запускать IC без ConEmu.
Возможно в следующей версии попробуем что-нибудь предпринять, чтоб обойти эту проблему.

**Comment by macik** [comment]
Понятно. Буду пока использовать «дроп» формат.

> Файл-флаг - это хорошо, но в случае падения IC файл-флаг останется не удаленным и пока пользователь вручную его не удалит IC работать не будет.

Учитывая, что параллельная работа скрипта это скорее нестандартная ситуация и предполагается запускать его в «эксклюзивном режиме», то на скорую руку идея такая — флагом запуска считать файл созданный во временной папке (системной или локальной) вида `image_catalyst.2015-11-21_00-23` (формат метки времени не принципиален можно timestamp). А соответственно в самом начале выполнения проверять на наличие файлов такого вида `image_catalyst.*`, если есть — выдаем аналогичное предупреждение.
После отработки скрипта (как успешном так и не успешном) — стираем все файлы (подтирая и «свой» и чужие, если они остались).
