### ISSUE TITLE
Is it available to create npm module based on this? 

### ISSUE THREAD

**Issue by lgg** [lorents17/iCatalyst#12]

**Comment by lorents17** [comment]
Вы хотите создать модуль npm на базе iCatalyst?

**Comment by lgg** [comment]
@lorents17 если честно, я пока что не совсем понял принципе работы. 
1. Почему запуск возможен только на windows или это уже не актуально? (я пришел со статей на хабре)
2. А так да, думаю было бы здорово сделать на данной основе npm модуль для оптимизации изображений.

**Comment by lorents17** [comment]
Проект основан на cmd, и для запуска требуется windows. Также ряд приложений есть только на windows. Есть мысли сделать проект совместимые с wine.

Если создавать npm модуль, то его необходимо будет писать с 0. Я могу рассказать про алгоритмы оптимизации- При необходимости.

Подскажите, Вы случайно не владеете языками c/c++?

**Comment by lgg** [comment]
@lorents17 к сожалению нет.
