### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by macik** [lorents17/iCatalyst#3]
«Операционная система — Windows XP SP3 32-bit и старше.»

Слово старше подразумевает более старые версии. Здесь же скорее всего имелись в виду более новые. (если я прав в английской версии надо тоже исправить).

**Comment by lorents17** [comment]
Да, Вы правы. На ваш взгляд, Как лучше написать?

**Comment by res2001** [comment]
Можно написать: "Win XP+" или "начиная от Win XP и выше"

**Comment by lorents17** [comment]
А если написать:
«Операционная система — Windows XP SP3 32-bit и позже».

**Comment by res2001** [comment]
Обычно употребляют "вышне", а не "позже". Просто посмотри описания любых программных продуктов, требования есть практически везде.

**Comment by lorents17** [comment]
сделал
