### ISSUE TITLE
Interlaced PNG support

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [lorents17/iCatalyst#4]
Any plans for interlaced PNG support? Currently iCatalyst optimizes all kinds of PNG into non-interlaced ones. It should at least warn the user that the resulting PNG would be a non-interlaced one. Or, even better - add an actual support for optimizing interlaced PNG.

**Comment by lorents17** [comment]
Regarding your comments totally agree, in the near future will add this information in the help. Support for interlaced PNG files do not work because of the software for optimizing PNG does not support this function

**Comment by ZimM-LostPolygon** [comment]
> Support for interlaced PNG files do not work because of the software for optimizing PNG does not support this function

Hm, is it? I remember Image Catalyst had the ability to optimize interlaced PNG in version 2.2 or something like that.

**Comment by lorents17** [comment]
To version 2.2 support was Interlaced, now from this function had to refuse for two reasons:
1. part of the PNG optimization programs do not support
2. PNG Interlaced always weigh more than PNG Non-Interlaced.

I'll think about the new optimization algorithm Interlaced PNG.

Can be done in version 2.2.

![2015-07-08_23-25-55](https://cloud.githubusercontent.com/assets/3890881/8581336/c1b1a95e-25c8-11e5-96ab-70843056d952.png)

Or add information in the config.ini. More inclined to the second option

**Comment by ZimM-LostPolygon** [comment]
I know that interlaced PNG always weigh more, but thing is, I have a web-page with 4 MB of large PNG images, and it's crucial to have then interlaced to improve user experience of loading, even though the resulting size is bigger. I understand that interlaced is much harder to compress and not all PNG optimizers can do that at all, but still: even basic interlaced PNG support would be a great addition. 
For now I'll just use version 2.2, thanks for the tip.
