### ISSUE TITLE
'tasklist' is not recognized 

### ISSUE THREAD

**Issue by macik** [lorents17/iCatalyst#8]
Error message:

``` shell
"C:\png_optimize\Image Catalyst\iCatalyst.bat" C:\dvp\users\marshal\files\tehn2015\
'tasklist' is not recognized as an internal or external command,                                                        
operable program or batch file.                                                                                         
```

**The strange thing** that `tasklist` is present in path and successfuly run from command line from iCatalyst or Image folder.

**Comment by macik** [comment]
Проблема похоже на моей стороне, т.к. попробовал и 2,5 и 2,6 версии. Суть одна — не может найти системные утилиты, которые есть в PATH (или по крайней мере отлично запускаются из командной строки).  
Версия 2,5 пишет, что не может найти `findstr` (который тоже отдельно прекрасно запускается).

В чем может быть дело ума не приложу.

**Comment by res2001** [comment]
Попробуй запустить IC в cmd.
Как запускаешь IC чтоб получилась ошибка?
Мысль в том, что, возможно у тебя x64 система и например для x32 приложений стандартные утилиты ком.строки не доступны, а для x64 - доступны. Или наоборот. Теоретически такое может быть.
Так же, возможно, если ты запускаешь каким-то специфическим способом, то переменная PATH имеет не стандартное значение.
Попробуй создать простейший батник со следующим содержимым:

```
echo %PATH%
pause
```

и запустить его таким же образом как ты запускаешь IC.
В выводе посмотри есть ли в PATH каталог c:\windows\system32

**Comment by macik** [comment]
Докладываю — похоже, как раз описанный случай:
- запускал и дропом и из комстроки
- система именно Win7x64
- переменная PATH присутствует, но `c:\windows\system32` там нет.

Добавил `c:\windows\system32` в скрипт (строка 37): 

```
PATH %apps%;c:\windows\system32;%PATH%
```

Все заработало.

Спасибо!

**Comment by res2001** [comment]
Когда нет системного каталога в PATH - это не нормально, может перестать работать много чего с труднодиагностируемыми ошибками.
Думаю, что есть смысл добавить в ручную: в свойствах компьютера -> дополнительные параметры системы -> Переменные среды
Далее, проверить в системном PATH наличие каталога %SystemRoot%\system32, если его там нет, то добавить.
Так же возможно, что системный PATH перекрывается пользовательским, тогда надо установки пользовательского PATH перенести в системный, предварительно проверив, чтоб они не дублировались. После чего пользовательский PATH удалить. Хотя этот вариант маловероятен, т.к. пользовательский PATH, обычно, добавляется к системному, а не заменяет его.

**Comment by macik** [comment]
Спасибо, за содействие. 
Путь добавил в системный Path. 
Странно, что его там не было.

Думаю тему можно закрывать.
